services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=demo'
      - 'POSTGRES_PASSWORD=${JDBC_DATABASE_PASSWORD}'
      - 'POSTGRES_USER=${JDBC_DATABASE_USERNAME}'
    ports:
      - '5432'
